coverage:
  precision: 1
  round: down
  range: "50...80"
  status:
    project:
      default:
        # Do not fail commits if the code coverage drops.
        target: 0%
        threshold: 100%
        base: auto
    patch:
      default:
        only_pulls: true
