# Have to manually unzip this (it gets double zipped) and add it
# onto the release after it gets created. Don't want actions with repo write.
name: Bundle Windows EXE

on:
  # Only trigger on release creation
  release:
    types:
      - created
  workflow_dispatch:


jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install cx_freeze

    - name: Bundle with cx_Freeze
      run: |
        python setup_cxfreeze.py build_exe
        pip install pip-licenses
        pip-licenses --format=plain-vertical --with-license-file --no-license-path --output-file=lib_licenses.txt
        python setup_cxfreeze.py finalize_cxfreeze

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
        name: hippolyzer-gui-windows-${{ github.sha }}
        path: ./dist/**
